version: '3.8'

services:
  api:
#    image: yasha/nest-api
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:yasha03@postgres:5432/api
      NODE_ENV: development
      PORT: 3000
    ports:
      - "8080:3000"
  postgres:
    image: postgres:12
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yasha03
      POSTGRES_DB: api
